name: Package
on: [push, pull_request]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run JUnit tests
        run: ./gradlew test
      - name: Export jar for all platforms
        uses: gradle/gradle-build-action@v1
        with:
          arguments: all_jar
      - name: Zip Windows release build
        run: |
          zip -r "StarMade_Launcher_Windows.zip" "release-builds/StarMade Launcher-win32-ia32"
      - name : Zip Mac release build
        run: |
          zip -r "StarMade_Launcher_Mac.zip" "release-builds/StarMade Launcher-darwin-x64"
      - name: Zip Linux release build
        run: |
          zip -r "StarMade_Launcher_Linux.zip" "release-builds/StarMade Launcher-linux-x64"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            **Changelog:**
          draft: true
          prerelease: false
      - name: Upload Release Asset Windows
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID
          asset_path: "StarMade_Launcher_Windows.zip"
          asset_name: "StarMade_Launcher_Windows.zip"
          asset_content_type: application/zip
      - name: Upload Release Asset Mac
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID
          asset_path: "StarMade_Launcher_Mac.zip"
          asset_name: "StarMade_Launcher_Mac.zip"
          asset_content_type: application/zip
      - name: Upload Release Asset Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID
          asset_path: "StarMade_Launcher_Linux.zip"
          asset_name: "StarMade_Launcher_Linux.zip"
          asset_content_type: application/zip