name: package.yml
on: [ push ]
jobs:
  build-executables:
    name: 'Build Executables'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Java 18'
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: 'Build Executable'
        run: |
          ./gradlew package
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./release-builds
      - name: 'Make Linux File Executable'
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x ./release-builds/linux/StarMade-Launcher
      - name: 'Make MacOS File Executable'
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x ./release-builds/macos/StarMade-Launcher.app/Contents/MacOS/StarMade-Launcher
  publish-executables:
    name: 'Publish Executables'
    runs-on: ubuntu-latest
    needs: build-executables
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./release-builds
      - name: 'Set Version Number'
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Create Linux Archive'
        run: |
          zip -r StarMade-Launcher-Linux.zip ./release-builds/linux
      - name: 'Create Windows Archive'
        run: |
          zip -r StarMade-Launcher-Windows.zip ./release-builds/windows
      - name: 'Create MacOS Archive'
        run: |
          zip -r StarMade-Launcher-MacOS.zip ./release-builds/macos
      - name: 'Create Release'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          draft: true
          prerelease: false
      - name: 'Upload Release Asset (Linux)'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: StarMade-Launcher-Linux.zip
          asset_name: StarMade-Launcher-Linux.zip
          asset_content_type: application/zip
      - name: 'Upload Release Asset (Windows)'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: StarMade-Launcher-Windows.zip
          asset_name: StarMade-Launcher-Windows.zip
          asset_content_type: application/zip
      - name: 'Upload Release Asset (MacOS)'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: StarMade-Launcher-MacOS.zip
          asset_name: StarMade-Launcher-MacOS.zip
          asset_content_type: application/zip